defaults:
  - _self_

exp_name: "flow_engine"
seed: 685


wandb:
  wandb_exp_name: ${exp_name}_${seed}

hydra:
  run:
    dir: ./logs/models/${exp_name}/${seed}

savepath:  ./logs/models/${exp_name}/${seed}

flow_model:
  network:
    base_channels: 32

  train:
    steps: 200000
    ema_update: 0.001
    batch_size: 128
    lr: 3e-4
    cosine_decay: False